version: '3.3'

services:
  mongo:
    image: mongo:4.4
    container_name: "mongo-container"
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db

mongo-e2e:
  image: mongo:4.4
  environment:
    MONGO_INITDB_ROOT_USERNAME: test
    MONGO_INITDB_ROOT_PASSWORD: root123
  ports:
    - 27017:27917
